export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_ATTEMPT = 'FETCH_DATA_ATTEMPT';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const FETCH_FILTER = 'FETCH_FILTER';
export const FETCH_FILTER_ATTEMPT = 'FETCH_FILTER_ATTEMPT';
export const FETCH_FILTER_SUCCESS = 'FETCH_FILTER_SUCCESS';
export const FETCH_FILTER_FAIL = 'FETCH_FILTER_FAIL';

